name: Generate Terraform Plan

# Build a plan on every PR against and push to master
# Additionally, apply the plan on every push to master
on: 
  pull_request:
    branches:
      - master
    paths:
      - infrastructure/*

jobs:
  create-plan:
    name: Generate Terraform Plan
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./infrastructure 

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        env:
          GITHUB_WORKSPACE: /opt/hostedtoolcache
        with:
          path: |
            /opt/hostedtoolcache/terraform
            /opt/hostedtoolcache/gcloud
          key: infrastructure

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Set up Terraform
        uses: jcuffe/setup-terraform@v2
      
      - name: Verify format
        run: terraform fmt

      - name: Initialize Terraform
        run: terraform init

      - name: Generate Plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_project: ${{ secrets.GCP_PROJECT }}

      - name: Store plan for application
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: ${{ env.WORKING_DIRECTORY }}/tfplan